---
upload_path: "/img/"
frontmatter_file_url_template: "/img/"
body_file_url_template: "/img/"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  press:
    default_front_matter_template: press
version: 0.31.1
