---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/shop
  label: Shop
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/artists
  label: Artists
  create: all
  match: "**/*"
- type: directory
  path: content/press
  label: Press
  create: all
  match: "**/*"
- type: directory
  path: content/apply
  label: Apply
  create: all
  match: "**/*"
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.31.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.31.1
  preview_output_directory: public
  output_directory: public
version: 0.31.1
